export class solicitudEncuesta{
    _id?: number;
    usuario: string;
    empresa: string;
    direccion: string;
    contacto: string;
    encargado: string;
    categoria: string;
    nombreArticulo: string;
    precioArticulo: number;
    marcaArticulo: string;
    descripcionArticulo: string;
    fechaInicio: String;
    fechaFinal: String;
    titulo: string;
    objetivo: string;
    poblacion: string;
    numeroEncuesta: number;
    pregunta1: string;
    pregunta2: string;
    pregunta3: string;
    pregunta4: string;
    pregunta5: string;
    pregunta6: string;
    pregunta7: string;
    pregunta8: string;
    pregunta9: string;
    pregunta10: string;
}